### ISSUE TITLE
someone help me 

### ISSUE THREAD

**Issue by LOLDERP** [SpongePowered/SpongeDocs#349]
when i run sudo gulp it gives me this error 

Last login: Fri Oct 23 16:14:37 on ttys002
Macbook-pro:~ Derp$ cd SpongeDocs
Macbook-pro:SpongeDocs Derp$ sudo gulp
[16:15:05] Using gulpfile ~/SpongeDocs/Gulpfile.js
[16:15:05] Starting 'clean'...
[16:15:05] Starting 'sphinx'...
[16:15:05] Starting 'watch'...
[16:15:06] Finished 'watch' after 81 ms
[16:15:06] Finished 'clean' after 109 ms
Running Sphinx v1.3.1
making output directory...

Exception occurred:
  File "conf.py", line 15, in <module>
ImportError: No module named sponge_docs_theme
The full traceback has been saved in /tmp/sphinx-err-MXfk_L.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
[16:15:06] 'sphinx' errored after 304 ms
[16:15:06] Error in plugin 'gulp-shell'
Message:
    Command `sphinx-build -b dirhtml source build/dirhtml` failed with exit code 1

**Comment by lukegb** [comment]
You haven't followed all the instructions in the readme - notably, you haven't done a `pip install` of the requirements.txt.

**Comment by LOLDERP** [comment]
oh

**Comment by LOLDERP** [comment]
thanks for telling me

**Comment by LOLDERP** [comment]
heres a log file

# Sphinx version: 1.3.1
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/application.py", line 126, in __init__
    confoverrides or {}, self.tags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 15, in <module>
ImportError: No module named sponge_docs_theme

**Comment by saladoc** [comment]
As lukegb said, you need to install the sponge-docs-theme module by running `pip install -r etc/requirements.txt`. The error message clearly indicates that the module is missing.

Also I don't think you need to use `sudo` to run gulp.
