### ISSUE TITLE
Issue installing pip dependencies

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeDocs#574]
While doing `pip install -r etc/requirements.txt`:

```
Collecting sphinx-intl==0.9.9 (from -r etc/requirements.txt (line 1))
  Using cached sphinx_intl-0.9.9-py2.py3-none-any.whl
Collecting sphinx==1.5.1 (from -r etc/requirements.txt (line 2))
  Using cached Sphinx-1.5.1-py2.py3-none-any.whl
Collecting colorama==0.3.7 (from -r etc/requirements.txt (line 3))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting pystache==0.5.4 (from -r etc/requirements.txt (line 4))
  Using cached pystache-0.5.4.tar.gz
Collecting requests==2.12.4 (from -r etc/requirements.txt (line 5))
  Using cached requests-2.12.4-py2.py3-none-any.whl
Collecting sphinx-JDLinker==1.3 (from -r etc/requirements.txt (line 6))
  Using cached sphinx-JDLinker-1.3.zip
Obtaining sponge_docs_theme from git+https://github.com/SpongePowered/sponge_docs_theme.git#egg=sponge_docs_theme (from -r etc/requirements.txt (line 7))
  Cloning https://github.com/SpongePowered/sponge_docs_theme.git to ./src/sponge-docs-theme
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/robert/projects/SpongeDocs/src/sponge-docs-theme/setup.py", line 2, in <module>
        import sponge_docs_theme
    ImportError: No module named sponge_docs_theme
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/robert/projects/SpongeDocs/src/sponge-docs-theme/
```

Pinging @Minecrell

**Comment by Inscrutable** [comment]
Is it possible that the change of base branch from ``master`` to ``stable`` has thrown things off?

**Comment by Minecrell** [comment]
The main branch on GitHub is still `master` because I'm unable to change it. Make sure you switch to the new `stable` branch before installing pip dependencies.

**Comment by Tzky** [comment]
It's ``pip install -r requirements.txt`` now, not ``pip install -r etc/requirements.txt``. Note the missing ``etc/``
